version: "3"
# คำสั่งทั้งหมด ที่จะใช้ run 
services: 
    database:
        image: mysql:5.7
        environment: 
            MYSQL_ROOT_PASSWORD: 1111
        volumes:
            - ./db_data:/var/lib/mysql
        networks: 
            - dockernumer
        restart: always
    php:
        depends_on: 
            - database
        build: 
            dockerfile: Dockerfile
            context: ./numer
        ports: 
            - 8080:80
        volumes: 
            - ./numer:/var/www/html
        restart: always
        networks: 
            - dockernumer
    phpmyadmin:
        depends_on:
            - database
        image: phpmyadmin/phpmyadmin
        environment: 
            PMA_ARBITRARY: 1
        networks:
            - dockernumer
        restart: always
        ports:
            - 8888:80  
    myreactapp:
        depends_on: 
            - database
            - php
        build: 
            dockerfile: Dockerfile
            context: ./projectnumer
        ports: 
            - 3000:3000
        restart: always
        networks: 
            - dockernumer
volumes:
    db_data:
networks: 
    dockernumer:            
